### ISSUE TITLE
Xarray's HTML repr is slightly broken in Colab

### ISSUE THREAD

**Issue by shoyer** [googlecolab/colabtools#1145]
- Describe the current behavior: From Colab

![image](https://user-images.githubusercontent.com/1217238/79079239-c216df80-7cc2-11ea-8965-9fef8f8301a1.png)

- Describe the expected behavior: From Jupyter

![image](https://user-images.githubusercontent.com/1217238/79079251-d65adc80-7cc2-11ea-9504-424d160df79c.png)

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome on OS X (same version for both)

- [Link to self-contained notebook that reproduces this issues](https://colab.research.google.com/drive/14xMgHYcfaYnkM9nWfvz-HlBdpxo4wX2M?usp=sharing) (only valid for internal Google users). Or create a new notebook with one cell:
    ```python
    ! pip install -q -U xarray
    import xarray
    xarray.tutorial.load_dataset('air_temperature')
    ```

My guess is that something about xarray's [CSS stylesheet](https://github.com/pydata/xarray/blob/v0.15.1/xarray/static/css/style.css) is broken in Colab. I'd love to fix this upstream, but if you have any tips about _why_  Colab could be styling this differently, it would be appreciated!

**Comment by blois** [comment]
The issue looks to be that Colab has a style rule:
```css
div.stream, div.pyout, div.output_text pre, pre.stream, pre.pyout {
    display: inline;
}
```

Which has a higher specificity rule than xarray's CSS style:
```
.xr-var-attrs, .xr-var-data {
    display: none;
    background-color: var(--xr-background-color) !important;
    padding-bottom: 5px !important;
}
```

And is overriding the `display: none` to be inline. 

A simple hack would be to use the CSS:
```css
.xr-var-attrs, .xr-var-data, .output_html .xr-var-data {
    display: none;
    background-color: var(--xr-background-color) !important;
    padding-bottom: 5px !important;
}
```

Colab probably should not specify the output_text class on HTML outputs.
