### ISSUE TITLE
Text of Jupyter Widgets unreadable in Dark Mode

### ISSUE THREAD

**Issue by EricESeverson** [googlecolab/colabtools#1895]
I am trying to use Jupyter widgets, but the text is still black when in dark mode.
The same error was described at https://github.com/jupyter-widgets/ipywidgets/issues/1812. I tried the suggested fix of adding 
`%%html
<style> .widget-readout{ color:white; } </style>` 
but this didn't change anything.

![image](https://user-images.githubusercontent.com/68571919/110177956-a0cb5000-7dba-11eb-9db9-5208c83201ec.png)

**Comment by drscotthawley** [comment]
Based on [this issue](https://github.com/jupyter-widgets/ipywidgets/issues/1812) and @shoyer's question [here](https://github.com/googlecolab/colabtools/issues/1214), I cooked up this little snippet that will only change the color if you're in dark mode, otherwise it'll keep the output text black. 

```Python
from IPython.display import HTML, display

def set_css_in_cell_output():
    display(HTML('''
        <style>
            html[theme=dark] {
                .jupyter-widgets {color: #d5d5d5 !important;}
                .widget-label {color: #d5d5d5 !important;}
            }
        </style>
    '''))

def set_css_in_cell_output():
    display(HTML('''
        <style>
            html[theme=dark] {
                .jupyter-widgets {color: #d5d5d5 !important;}
                .widget-label {color: #d5d5d5 !important;}
            }
        </style>
    '''))

def ipython_dark_mode():
    get_ipython().events.register('pre_run_cell', set_css_in_cell_output)

ipython_dark_mode()
```

**Comment by blois** [comment]
I put in two changes which will hopefully improve this a bit, they should be arriving in the next day or two-

- The CSS for the widgets no longer has variables expanded, so you can overwrite the Jupyter CSS properties and have them affect all widgets.
-  Defaulted a few of the properties to reflect Colab themes
    ```css
    :root {
      --jp-widgets-color: var(--colab-primary-text-color);
      --jp-layout-color2: var(--colab-secondary-surface-color);
      --jp-ui-font-color1: var(--colab-primary-text-color);
      --jp-widgets-input-background-color: var(--colab-secondary-surface-color);
    }
    ```
