### ISSUE TITLE
How to disable blinking cursor in a cell?

### ISSUE THREAD

**Issue by al-yakubovich** [googlecolab/colabtools#987]

**Comment by tnovikoff** [comment]
Thank you for the feature request. Tracking internally at b/149117189.

**Comment by timmb** [comment]
Also can't deal with a blinking cursor.

@al-yakubovich I have found a workaround for this. Using Firefox with the Stylus extension, make a custom CSS rule targeting research.google.com with this:

```css
.focused .cursor {
    visibility: inherit !important;
    background-color: #ff009d !important;
}
```

(Colour change is optional but helps you see the cursor.)
